const fs = require('fs');
const lines = fs.readFileSync('src/pages/TVPage.jsx', 'utf8').split('\n');
const newLines = [
  ...lines.slice(0, 1671),
  '          {playing && selectedEp && (',
  '            <div className="section">',
  '              <div',
  '                style={{',
  '                  marginBottom: 12,',
  '                  display: "flex",',
  '                  alignItems: "center",',
  '                  gap: 12,',
  '                }}',
  '              >',
  '                <span className="tag tag-red">',
  '                  Season {selectedSeason} · E{selectedEp.episode_number}',
  '                </span>',
  '                <span style={{ fontSize: 14, fontWeight: 500 }}>',
  '                  {selectedEp.name}',
  '                </span>',
  '                {currentEpWatched ? (',
  '                  <button',
  '                    className="btn btn-ghost watched-btn"',
  '                    style={{ marginLeft: "auto" }}',
  '                    onClick={() => onMarkUnwatched?.(currentProgressKey)}',
  '                  >',
  '                    <WatchedIcon size={14} /> Watched',
  '                  </button>',
  '                ) : (',
  '                  <button',
  '                    className="btn btn-ghost"',
  '                    style={{ marginLeft: "auto" }}',
  '                    onClick={() => onMarkWatched?.(currentProgressKey)}',
  '                  >',
  '                    ✓ Mark Watched',
  '                  </button>',
  '                )}',
  '              </div>',
  '              <div className="player-wrap" style={{ position: "relative", width: "100%", paddingBottom: "56.25%", background: "#000" }}>',
  '                <iframe',
  '                  src={`https://vidsrc.pro/embed/tv/${item.id}/${selectedSeason}/${selectedEp.episode_number}`}',
  '                  style={{ position: "absolute", top: 0, left: 0, width: "100%", height: "100%", border: "none" }}',
  '                  allowFullScreen',
  '                />',
  '              </div>',
  '            </div>',
  '          )}',
  ...lines.slice(2336)
];
fs.writeFileSync('src/pages/TVPage.jsx', newLines.join('\n'));
